# Generated by Django 5.0.6 on 2024-06-21 10:48

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Full Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('service_description', models.TextField(verbose_name='Service Description')),
                ('category', models.CharField(choices=[('Computer Vision', 'Computer Vision'), ('Others', 'Others')], max_length=255, verbose_name='Service Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['email'], name='email_idx')],
            },
        ),
    ]
